---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    dnf:
      state: latest
      update_cache: yes

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
